word_list = [
    'kast',
    'brood',
    'slaapkamer',
    'vacinatie',
    'corona',
    'school',
    'schoenen',
    'tafel',
    'kleding',
    'computer',
    'regen',
    'omweer',
    'tas',
    'onderwijs']